# red_hue_strength: 0.85

output_dir: data/eval_logs/groot_plain
seed: 0
env:
  type: libero
  task: libero_10
  # - libero_goal
  # - libero_10
  # - libero_spatial
  max_parallel_tasks: 1
eval:
  batch_size: 10
  n_episodes: 10
  use_async_envs: true
policy:
  type: groot
  pretrained_path: ar0s/groot_libero_10
  # n_action_steps: 10
  # n_action_steps: 10


